name: Update Employee JSON

on:
  repository_dispatch:
    types: [update-employees]

jobs:
  update-json:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Update employee data
        run: |
          echo '${{ github.event.client_payload.json }}' > employees.json

      - name: Commit and push
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "actions@github.com"
          git add employees.json
          git commit -m "Update employee data"
          git push
